export const homepageQuery = `*[_type == "homepage"][0]{
  companyName,
  phone,
  email,
  address,
  footerText,
  tagline,
  copyrightText,
  disclaimer1,
  disclaimer2,
  disclaimer3,
  primaryCtaText,
  primaryCtaLink
  heroTitle,
  heroSubtitle,
  heroButtonText,
  heroImage,
  ctaTitle,
  ctaSubtitle,
  ctaButtonText,
  whyRscTitle,
  whyRscSubtitle,
  recentDealsTitle,
  recentDealsSubtitle,
  recentDealsItems[]{
  image,
  type,
  location,
  amount,
  note,
  ltc
},
  whyRscItems[]{
  title,
  description
  },
  faqItems[]{
    question,
    answer
  },
  loanPrograms[]{
    title,
    description
  }
  }`;

export const siteSettingsQuery = `*[_type == "siteSettings"][0]{
  companyName,
  primaryCtaText,
  primaryCtaLink
}`;
